# Generated by Django 3.2.7 on 2021-10-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_alter_cpu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'RAM', 'verbose_name_plural': 'RAM'},
        ),
    ]
