# Generated by Django 3.2.7 on 2021-10-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_auto_20211013_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('interface', models.CharField(choices=[('ISA', '8-bit ISA'), ('ISA16', '16-bit ISA'), ('VLB', 'VLB'), ('PCI', 'PCI'), ('PCIE1', 'PCIe x1'), ('PCIE4', 'PCIe x4'), ('PCIE8', 'PCIe x8'), ('PCI16', 'PCIe x16')], default='ISA', max_length=6)),
                ('io_panel', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('top_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='expansion_cards')),
                ('bottom_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='expansion_cards')),
                ('io_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='expansion_cards')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('form_factor', models.CharField(choices=[('AT', 'AT'), ('BABYAT', 'Baby AT'), ('ATX', 'ATX'), ('EATX', 'E-ATX'), ('MATX', 'Micro ATX'), ('ITX', 'Mini ITX'), ('PROP', 'Proprietary')], default='ATX', max_length=6)),
                ('socket', models.CharField(max_length=200)),
                ('isa', models.IntegerField(default=0)),
                ('isa16', models.IntegerField(default=0)),
                ('vlb', models.IntegerField(default=0)),
                ('pci', models.IntegerField(default=0)),
                ('agp', models.IntegerField(default=0)),
                ('pice1', models.IntegerField(default=0)),
                ('pcie4', models.IntegerField(default=0)),
                ('pcie8', models.IntegerField(default=0)),
                ('pcie16', models.IntegerField(default=0)),
                ('ram', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('top_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='motherboards')),
                ('bottom_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='motherboards')),
                ('io_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='motherboards')),
            ],
        ),
        migrations.AlterModelOptions(
            name='soundcard',
            options={},
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='io',
            new_name='io_img',
        ),
        migrations.RenameField(
            model_name='soundcard',
            old_name='io',
            new_name='io_img',
        ),
    ]
