# Generated by Django 3.2.7 on 2021-10-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('speed', models.IntegerField()),
                ('socket', models.CharField(max_length=200)),
                ('cores', models.IntegerField()),
                ('hyperthreading', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('top_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='cpus')),
                ('bottom_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='cpus')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FPM', 'FPM'), ('EDO', 'EDO'), ('SDRAM', 'SDRAM'), ('DDR1', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], default='FPM', max_length=5)),
                ('interface', models.CharField(choices=[('SIMM30', '30-pin SIMM'), ('SIMM72', '72-pin SIMM'), ('DIMM', 'DIMM'), ('SODIMM', 'SO-DIMM')], default='SIMM30', max_length=6)),
                ('size', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('ecc', models.BooleanField()),
            ],
        ),
    ]
