# Generated by Django 3.2.7 on 2021-10-12 23:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9e6a3c67-dc5b-4b5c-ba1d-545ba6744609'), editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('speed', models.IntegerField()),
                ('socket', models.CharField(max_length=200)),
                ('cores', models.IntegerField()),
                ('hyperthreading', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('32a75ba0-91ea-4ca3-b2ce-0870b8586e23'), editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FPM', 'FPM'), ('EDO', 'EDO'), ('SDRAM', 'SDRAM'), ('DDR1', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], default='FPM', max_length=5)),
                ('interface', models.CharField(choices=[('SIMM30', '30-pin SIMM'), ('SIMM72', '72-pin SIMM'), ('DIMM', 'DIMM'), ('SODIMM', 'SO-DIMM')], default='SIMM30', max_length=6)),
                ('size', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
