# Generated by Django 3.2.7 on 2021-10-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='bottom_img',
            field=models.ImageField(max_length=255, null=True, upload_to='cpus'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='top_img',
            field=models.ImageField(max_length=255, null=True, upload_to='cpus'),
        ),
    ]
