# Generated by Django 3.2.7 on 2021-10-12 23:20

from django.db import migrations, models
import hardware.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='bottom_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=hardware.models.GetImageName('cpus', '1d728626-a6e3-4dc6-ba84-f522ce725410', 'bottom')),
        ),
        migrations.AddField(
            model_name='cpu',
            name='top_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=hardware.models.GetImageName('cpus', '1d728626-a6e3-4dc6-ba84-f522ce725410', 'top')),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d728626-a6e3-4dc6-ba84-f522ce725410'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ram',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c155651-1b59-4c08-ace9-001192bdacdd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
