# Generated by Django 3.2.7 on 2021-10-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20211011_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
