# Generated by Django 3.2.7 on 2021-10-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_alter_cpu_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='bottom_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cpus'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='top_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cpus'),
        ),
    ]
