# Generated by Django 3.2.7 on 2021-10-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_alter_ram_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('interface', models.CharField(choices=[('ISA', '8-bit ISA'), ('ISA16', '16-bit ISA'), ('VLB', 'VLB'), ('PCI', 'PCI'), ('AGP', 'AGP'), ('AGP2', 'AGP 2x'), ('AGP4', 'AGP 4x'), ('AGP8', 'AGP 8x'), ('PCIE', 'PCI Express')], default='ISA', max_length=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('top_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='gpus')),
                ('bottom_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='gpus')),
                ('io', models.ImageField(blank=True, max_length=255, null=True, upload_to='gpus')),
            ],
            options={
                'verbose_name': 'GPU',
                'verbose_name_plural': 'GPUs',
            },
        ),
    ]
