# Generated by Django 3.2.7 on 2021-10-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_gpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('SB Compatibility', models.CharField(max_length=200)),
                ('interface', models.CharField(choices=[('ISA', '8-bit ISA'), ('ISA16', '16-bit ISA'), ('PCI', 'PCI'), ('PCIE1', 'PCIe x1')], default='ISA', max_length=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('top_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='sound_cards')),
                ('bottom_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='sound_cards')),
                ('io', models.ImageField(blank=True, max_length=255, null=True, upload_to='sond_cards')),
            ],
            options={
                'verbose_name': 'Sound Card',
                'verbose_name_plural': 'Sound Cards',
            },
        ),
        migrations.AlterField(
            model_name='gpu',
            name='interface',
            field=models.CharField(choices=[('ISA', '8-bit ISA'), ('ISA16', '16-bit ISA'), ('VLB', 'VLB'), ('PCI', 'PCI'), ('AGP', 'AGP'), ('AGP2', 'AGP 2x'), ('AGP4', 'AGP 4x'), ('AGP8', 'AGP 8x'), ('PCIE16', 'PCIe x16')], default='ISA', max_length=6),
        ),
    ]
