# Generated by Django 3.2.7 on 2021-10-13 23:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_auto_20211013_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('wireless', models.BooleanField()),
                ('speed', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('G', 'G'), ('N', 'N'), ('AC', 'AC'), ('AX', 'AX'), ('10', '10 Megabit'), ('100', '10/100 Megabit'), ('1000', 'Gigabit'), ('2500', '2.5 Gigabit'), ('10G', '10 Gigabit')], default='10', max_length=7)),
                ('interface', models.CharField(choices=[('ISA', '8-bit ISA'), ('ISA16', '16-bit ISA'), ('VLB', 'VLB'), ('PCI', 'PCI'), ('PCIE1', 'PCIe x1'), ('PCIE4', 'PCIe x4'), ('PCIE8', 'PCIe x8'), ('PCI16', 'PCIe x16')], default='ISA', max_length=6)),
                ('aui', models.IntegerField(default=0)),
                ('bnc', models.IntegerField(default=0)),
                ('tp', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('top_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='nics')),
                ('bottom_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='nics')),
                ('io_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='nics')),
            ],
            options={
                'verbose_name': 'NIC',
                'verbose_name_plural': 'NICs',
            },
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AT', 'AT'), ('BABYAT', 'Baby AT'), ('ATX', 'ATX'), ('EATX', 'E-ATX'), ('MATX', 'Micro ATX'), ('ITX', 'Mini ITX'), ('PROP', 'Proprietary')], max_length=200),
        ),
    ]
