# Generated by Django 3.2.7 on 2021-10-14 16:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_alter_motherboard_form_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('mb_support', multiselectfield.db.fields.MultiSelectField(choices=[('AT', 'AT'), ('BABYAT', 'Baby AT'), ('ATX', 'ATX'), ('EATX', 'E-ATX'), ('MATX', 'Micro ATX'), ('ITX', 'Mini ITX'), ('PROP', 'Proprietary')], default='ATX', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('M', 'Mouse'), ('KB', 'Keyboard'), ('ZIP', 'Zip Drive'), ('GAME', 'Gameport'), ('MIDI', 'Midi')], default='M', max_length=10)),
                ('interface', multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB')], default='USB', max_length=42)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('wattage', models.IntegerField()),
                ('spec', models.CharField(choices=[('AT', 'AT'), ('AXT20', '20-pin ATX'), ('ATX24', '24-pin ATX'), ('ATX2_4', '20+4-pin ATX')], default='AT', max_length=6)),
                ('minus5v', models.BooleanField()),
                ('molex', models.IntegerField(default=0)),
                ('floppy', models.IntegerField(default=0)),
                ('sata', models.IntegerField(default=0)),
                ('cpu4pin', models.IntegerField(default=0)),
                ('cpu8pin', models.IntegerField(default=0)),
                ('pcie6pin', models.IntegerField(default=0)),
                ('pcie8pin', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='psus')),
            ],
            options={
                'verbose_name': 'PSU',
                'verbose_name_plural': 'PSUs',
            },
        ),
        migrations.AddField(
            model_name='gpu',
            name='cga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='dp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='dvi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='hdmi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='mda',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='other',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='vga',
            field=models.IntegerField(default=0),
        ),
    ]
