# Generated by Django 3.2.8 on 2021-10-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_auto_20211014_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='mb_support',
            new_name='Motherboard Compatibility',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='bottom_img',
            new_name='Bottom Image',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='top_img',
            new_name='Top Image',
        ),
        migrations.RenameField(
            model_name='expansioncard',
            old_name='bottom_img',
            new_name='Bottom Image',
        ),
        migrations.RenameField(
            model_name='expansioncard',
            old_name='io_img',
            new_name='IO Panel',
        ),
        migrations.RenameField(
            model_name='expansioncard',
            old_name='io_panel',
            new_name='IO Panel (comma separated)',
        ),
        migrations.RenameField(
            model_name='expansioncard',
            old_name='top_img',
            new_name='Top Image',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='bottom_img',
            new_name='Bottom Image',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='cga',
            new_name='CGA Ports',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='dp',
            new_name='DVI Ports',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='dvi',
            new_name='Displayport Ports',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='hdmi',
            new_name='HDMI Pors',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='io_img',
            new_name='IO Panel',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='mda',
            new_name='MDA Ports',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='other',
            new_name='Other Ports (Use notes)',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='top_img',
            new_name='Top Image',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='vga',
            new_name='VGA Ports',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='agp',
            new_name='16-bit ISA Slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='isa',
            new_name='8-bit ISA Slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='isa16',
            new_name='AGP Slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='bottom_img',
            new_name='Bottom Image',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='io_img',
            new_name='IO Panel',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='pci',
            new_name='PCI Slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='pcie16',
            new_name='PCIe x1 Slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='pcie4',
            new_name='PCIe x16 Slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='pcie8',
            new_name='PCIe x4 Slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='pice1',
            new_name='PCIe x8 Slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='ram',
            new_name='RAM Slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='top_img',
            new_name='Top Image',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='vlb',
            new_name='VLB Slots',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='aui',
            new_name='AUI Ports',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='bnc',
            new_name='BNC Ports',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='bottom_img',
            new_name='Bottom Image',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='tp',
            new_name='Ethernet Ports',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='io_img',
            new_name='IO Panel',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='top_img',
            new_name='Top Image',
        ),
        migrations.RenameField(
            model_name='psu',
            old_name='minus5v',
            new_name='-5v rail',
        ),
        migrations.RenameField(
            model_name='psu',
            old_name='cpu4pin',
            new_name='4-pin CPU Connectors',
        ),
        migrations.RenameField(
            model_name='psu',
            old_name='cpu8pin',
            new_name='6-pin PCIe Connectors',
        ),
        migrations.RenameField(
            model_name='psu',
            old_name='floppy',
            new_name='8-pin CPU Connectors',
        ),
        migrations.RenameField(
            model_name='psu',
            old_name='molex',
            new_name='8-pin PCIe Connectors',
        ),
        migrations.RenameField(
            model_name='psu',
            old_name='pcie6pin',
            new_name='Floppy Connectors',
        ),
        migrations.RenameField(
            model_name='psu',
            old_name='pcie8pin',
            new_name='Molex Connectors',
        ),
        migrations.RenameField(
            model_name='psu',
            old_name='sata',
            new_name='SATA Connectors',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='size',
            new_name='Size (MB)',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='speed',
            new_name='Speed (ns or MHz)',
        ),
        migrations.RenameField(
            model_name='soundcard',
            old_name='bottom_img',
            new_name='Bottom Image',
        ),
        migrations.RenameField(
            model_name='soundcard',
            old_name='io_img',
            new_name='IO Panel',
        ),
        migrations.RenameField(
            model_name='soundcard',
            old_name='top_img',
            new_name='Top Image',
        ),
    ]
