# Generated by Django 3.2.7 on 2021-10-14 19:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_auto_20211014_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='Motherboard Compatibility',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='Bottom Image',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='Top Image',
        ),
        migrations.RemoveField(
            model_name='expansioncard',
            name='Bottom Image',
        ),
        migrations.RemoveField(
            model_name='expansioncard',
            name='IO Panel',
        ),
        migrations.RemoveField(
            model_name='expansioncard',
            name='IO Panel (comma separated)',
        ),
        migrations.RemoveField(
            model_name='expansioncard',
            name='Top Image',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='Bottom Image',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='CGA Ports',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='DVI Ports',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='Displayport Ports',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='HDMI Pors',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='IO Panel',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='MDA Ports',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='Other Ports (Use notes)',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='Top Image',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='VGA Ports',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='16-bit ISA Slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='8-bit ISA Slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='AGP Slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='Bottom Image',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='IO Panel',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='PCI Slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='PCIe x1 Slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='PCIe x16 Slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='PCIe x4 Slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='PCIe x8 Slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='RAM Slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='Top Image',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='VLB Slots',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='AUI Ports',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='BNC Ports',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='Bottom Image',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='Ethernet Ports',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='IO Panel',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='Top Image',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='-5v rail',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='4-pin CPU Connectors',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='6-pin PCIe Connectors',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='8-pin CPU Connectors',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='8-pin PCIe Connectors',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='Floppy Connectors',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='Molex Connectors',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='SATA Connectors',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='Size (MB)',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='Speed (ns or MHz)',
        ),
        migrations.RemoveField(
            model_name='soundcard',
            name='Bottom Image',
        ),
        migrations.RemoveField(
            model_name='soundcard',
            name='IO Panel',
        ),
        migrations.RemoveField(
            model_name='soundcard',
            name='SB Compatibility',
        ),
        migrations.RemoveField(
            model_name='soundcard',
            name='Top Image',
        ),
        migrations.AddField(
            model_name='case',
            name='mb_support',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AT', 'AT'), ('BABYAT', 'Baby AT'), ('ATX', 'ATX'), ('EATX', 'E-ATX'), ('MATX', 'Micro ATX'), ('ITX', 'Mini ITX'), ('PROP', 'Proprietary')], default='ATX', max_length=32, verbose_name='Motherboard Compatibility'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='bottom_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cpus', verbose_name='Bottom Image'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='top_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cpus', verbose_name='Top Image'),
        ),
        migrations.AddField(
            model_name='expansioncard',
            name='bottom_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='expansion_cards', verbose_name='Bottom Image'),
        ),
        migrations.AddField(
            model_name='expansioncard',
            name='io_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='expansion_cards', verbose_name='IO Panel'),
        ),
        migrations.AddField(
            model_name='expansioncard',
            name='io_panel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IO Panel (comma separated)'),
        ),
        migrations.AddField(
            model_name='expansioncard',
            name='top_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='expansion_cards', verbose_name='Top Image'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='bottom_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='gpus', verbose_name='Bottom Image'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='cga',
            field=models.IntegerField(default=0, verbose_name='CGA Ports'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='dp',
            field=models.IntegerField(default=0, verbose_name='Displayport Ports'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='dvi',
            field=models.IntegerField(default=0, verbose_name='DVI Ports'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='hdmi',
            field=models.IntegerField(default=0, verbose_name='HDMI Pors'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='io_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='gpus', verbose_name='IO Panel'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='mda',
            field=models.IntegerField(default=0, verbose_name='MDA Ports'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='other',
            field=models.IntegerField(default=0, verbose_name='Other Ports (Use notes)'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='top_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='gpus', verbose_name='Top Image'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='vga',
            field=models.IntegerField(default=0, verbose_name='VGA Ports'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='agp',
            field=models.IntegerField(default=0, verbose_name='AGP Slots'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='bottom_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='motherboards', verbose_name='Bottom Image'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='io_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='motherboards', verbose_name='IO Panel'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='isa',
            field=models.IntegerField(default=0, verbose_name='8-bit ISA Slots'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='isa16',
            field=models.IntegerField(default=0, verbose_name='16-bit ISA Slots'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pci',
            field=models.IntegerField(default=0, verbose_name='PCI Slots'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie16',
            field=models.IntegerField(default=0, verbose_name='PCIe x16 Slots'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie4',
            field=models.IntegerField(default=0, verbose_name='PCIe x4 Slots'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie8',
            field=models.IntegerField(default=0, verbose_name='PCIe x8 Slots'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pice1',
            field=models.IntegerField(default=0, verbose_name='PCIe x1 Slots'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ram',
            field=models.IntegerField(default=0, verbose_name='RAM Slots'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='top_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='motherboards', verbose_name='Top Image'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='vlb',
            field=models.IntegerField(default=0, verbose_name='VLB Slots'),
        ),
        migrations.AddField(
            model_name='nic',
            name='aui',
            field=models.IntegerField(default=0, verbose_name='AUI Ports'),
        ),
        migrations.AddField(
            model_name='nic',
            name='bnc',
            field=models.IntegerField(default=0, verbose_name='BNC Ports'),
        ),
        migrations.AddField(
            model_name='nic',
            name='bottom_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='nics', verbose_name='Bottom Image'),
        ),
        migrations.AddField(
            model_name='nic',
            name='io_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='nics', verbose_name='IO Panel'),
        ),
        migrations.AddField(
            model_name='nic',
            name='top_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='nics', verbose_name='Top Image'),
        ),
        migrations.AddField(
            model_name='nic',
            name='tp',
            field=models.IntegerField(default=0, verbose_name='Ethernet Ports'),
        ),
        migrations.AddField(
            model_name='psu',
            name='cpu4pin',
            field=models.IntegerField(default=0, verbose_name='4-pin CPU Connectors'),
        ),
        migrations.AddField(
            model_name='psu',
            name='cpu8pin',
            field=models.IntegerField(default=0, verbose_name='8-pin CPU Connectors'),
        ),
        migrations.AddField(
            model_name='psu',
            name='floppy',
            field=models.IntegerField(default=0, verbose_name='Floppy Connectors'),
        ),
        migrations.AddField(
            model_name='psu',
            name='minus5v',
            field=models.BooleanField(default=False, verbose_name='-5v rail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psu',
            name='molex',
            field=models.IntegerField(default=0, verbose_name='Molex Connectors'),
        ),
        migrations.AddField(
            model_name='psu',
            name='pcie6pin',
            field=models.IntegerField(default=0, verbose_name='6-pin PCIe Connectors'),
        ),
        migrations.AddField(
            model_name='psu',
            name='pcie8pin',
            field=models.IntegerField(default=0, verbose_name='8-pin PCIe Connectors'),
        ),
        migrations.AddField(
            model_name='psu',
            name='sata',
            field=models.IntegerField(default=0, verbose_name='SATA Connectors'),
        ),
        migrations.AddField(
            model_name='ram',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Size (MB)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='Speed (ns or MHz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundcard',
            name='bottom_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='sound_cards', verbose_name='Bottom Image'),
        ),
        migrations.AddField(
            model_name='soundcard',
            name='io_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='sond_cards', verbose_name='IO Panel'),
        ),
        migrations.AddField(
            model_name='soundcard',
            name='sb',
            field=models.CharField(default='None', max_length=200, verbose_name='SB Compatibility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundcard',
            name='top_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='sound_cards', verbose_name='Top Image'),
        ),
    ]
