# Generated by Django 4.0.7 on 2022-10-30 13:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_auto_20211014_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CABLE', 'Cable'), ('IO', 'I/O Bracket'), ('ADAPT', 'Adapter')], default='CABLE', max_length=10)),
                ('interface', multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('OTHER', 'Other')], default='OTHER', max_length=48)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cable, Adapter, I/O Bracket',
                'verbose_name_plural': 'Cables, Adapters, IO Brackets',
            },
        ),
        migrations.AlterField(
            model_name='nic',
            name='interface',
            field=models.CharField(choices=[('ISA', '8-bit ISA'), ('ISA16', '16-bit ISA'), ('VLB', 'VLB'), ('PCI', 'PCI'), ('PCIE1', 'PCIe x1'), ('PCIE4', 'PCIe x4'), ('PCIE8', 'PCIe x8'), ('PCI16', 'PCIe x16'), ('M2', 'M.2 2230')], default='ISA', max_length=6),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='interface',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('OTHER', 'Other')], default='USB', max_length=48),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='type',
            field=models.CharField(choices=[('M', 'Mouse'), ('KB', 'Keyboard'), ('ZIP', 'Zip Drive'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('SPK', 'Speakers'), ('LCD', 'LCD'), ('CRT', 'CRT')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ecc',
            field=models.BooleanField(verbose_name='ECC'),
        ),
    ]
