# Generated by Django 4.0.7 on 2022-10-31 11:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_cables_alter_nic_interface_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cables',
            old_name='interface',
            new_name='interface_a',
        ),
        migrations.AddField(
            model_name='cables',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cables',
            name='interface_b',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('OTHER', 'Other')], default='OTHER', max_length=48),
        ),
    ]
