# Generated by Django 4.0.7 on 2022-10-31 11:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0014_alter_cables_description_alter_cables_interface_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cables',
            name='image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cables'),
        ),
        migrations.AddField(
            model_name='cables',
            name='image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cables'),
        ),
        migrations.AddField(
            model_name='cables',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='peripheral',
            name='image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='peripherals'),
        ),
        migrations.AddField(
            model_name='peripheral',
            name='image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='peripherals'),
        ),
        migrations.AddField(
            model_name='peripheral',
            name='image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='perihperals'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='interface',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('PIN', 'PIN Connector'), ('OTHER', 'Other')], default='USB', max_length=52),
        ),
    ]
