# Generated by Django 4.0.7 on 2022-11-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0015_cables_image_1_cables_image_2_cables_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peripheral',
            name='name',
            field=models.CharField(default='generic', max_length=200),
            preserve_default=False,
        ),
    ]
