# Generated by Django 4.0.7 on 2022-11-06 13:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0016_peripheral_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cables',
            name='interface_a',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('PIN', 'Pin Connector'), ('MM35', '3.5MM'), ('MM63', '6.3MM'), ('RCA', 'RCA'), ('OTHER', 'Other')], default='OTHER', max_length=66, verbose_name='Interface A'),
        ),
        migrations.AlterField(
            model_name='cables',
            name='interface_b',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('PIN', 'Pin Connector'), ('MM35', '3.5MM'), ('MM63', '6.3MM'), ('RCA', 'RCA'), ('OTHER', 'Other')], default='OTHER', max_length=66, verbose_name='Interface B'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='interface',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('PIN', 'Pin Connector'), ('MM35', '3.5MM'), ('MM63', '6.3MM'), ('RCA', 'RCA'), ('OTHER', 'Other')], default='USB', max_length=66),
        ),
    ]
