# Generated by Django 4.0.7 on 2022-11-07 21:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0018_alter_peripheral_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cables',
            name='description',
        ),
        migrations.AddField(
            model_name='cables',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cables',
            name='interface_a',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('OTHER', 'Other'), ('DB9SM', 'DB-9 Serial Male'), ('DB9SF', 'DB-9 Serial Female'), ('DB25PM', 'DB-25 Parallel Male'), ('DB25PF', 'DB-25 Parallel Female'), ('AMPH36M', '36-Pin Amphenol Parallel Male'), ('AMPH36F', '36-Pin Amphenol Parallel Female'), ('DB25SM', 'DB-25 SCSI Male'), ('DB25SF', 'DB-25 SCSI Female'), ('AMPH50M', '50-Pin Amphenol SCSI Male'), ('AMPH50F', '50-Pin Amphenol SCSI Female'), ('VHDCI68M', 'VHDCI-68 SCSI Male'), ('VHDCI68F', 'VHDCI-68 SCSI Female'), ('DB15GM', 'DB-15 Gameport Male'), ('DB15GF', 'DB-15 Gameport Female'), ('USBAM', 'USB A Male'), ('USBAF', 'USB A Female'), ('USBBM', 'USB B Male'), ('USBBF', 'USB B Female'), ('USBMICROBM', 'USB Micro B Male'), ('USBMICROBF', 'USB Micro B Female'), ('USBMINIBM', 'USB Mini B Male'), ('USBMINIBF', 'USB Mini B Female'), ('DIN5M', '5-Pin DIN Male'), ('DIN5F', '5-Pin DIN Female'), ('ADBM', 'ADB Male'), ('ADBF', 'ADB Female'), ('PS2M', 'PS/2 Male'), ('PS2F', 'PS/2 Female'), ('PIN4', '4-Pin Connector'), ('PIN6', '6-Pin Connector'), ('PIN8', '8-Pin Connector'), ('MM35M', '3.5MM Male'), ('MM35F', '3.5MM Female'), ('MM63M', '6.3MM Male'), ('MM63F', '6.3MM Female'), ('XLRM', 'XLR Male'), ('XLRF', 'XLR Female'), ('RCAM', 'RCA Male'), ('RCAF', 'RCA Female'), ('MDAM', 'DB-9 MDA Male'), ('MDAF', 'DB-9 MDA Female'), ('CGAM', 'DB-9 CGA Male'), ('CGAF', 'DB-9 CGA Female'), ('EGAM', 'DB-9 EGA Male'), ('EGAF', 'DB-9 EGA Female'), ('VGAM', 'DB-15 VGA Male'), ('VGAF', 'DB-15 VGA Female'), ('DVIDDM', 'DVI-D Dual-Link Male'), ('DVIDDF', 'DVI-D Dual-Link Female'), ('DVIDSM', 'DVI-D Single-Link Male'), ('DVIDSF', 'DVI-D Single-Link Female'), ('DVIIDM', 'DVI-I Dual-Link Male'), ('DVIIDF', 'DVI-I Dual-Link Female'), ('DVIISM', 'DVI-I Single-Link Male'), ('DVIISF', 'DVI-I Single-Link Female'), ('DVIAM', 'DVI-A Male'), ('DVIAF', 'DVI-A Female'), ('HDMIM', 'HDMI Male'), ('HDMIF', 'HDMI Female'), ('MINIHDMIM', 'Mini HDMI Male'), ('MINIHDMIF', 'Mini HDMI Female'), ('MICROHDMIM', 'Micro HDMI Male'), ('MICROHDMIF', 'Micro HDMI Female'), ('DPM', 'DisplayPort Male'), ('DPF', 'DisplayPort Female'), ('MINIDPM', 'Mini DisplayPort Male'), ('MINIDPF', 'Mini DisplayPort Female')], default='OTHER', max_length=452, verbose_name='Interface A'),
        ),
        migrations.AlterField(
            model_name='cables',
            name='interface_b',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('OTHER', 'Other'), ('DB9SM', 'DB-9 Serial Male'), ('DB9SF', 'DB-9 Serial Female'), ('DB25PM', 'DB-25 Parallel Male'), ('DB25PF', 'DB-25 Parallel Female'), ('AMPH36M', '36-Pin Amphenol Parallel Male'), ('AMPH36F', '36-Pin Amphenol Parallel Female'), ('DB25SM', 'DB-25 SCSI Male'), ('DB25SF', 'DB-25 SCSI Female'), ('AMPH50M', '50-Pin Amphenol SCSI Male'), ('AMPH50F', '50-Pin Amphenol SCSI Female'), ('VHDCI68M', 'VHDCI-68 SCSI Male'), ('VHDCI68F', 'VHDCI-68 SCSI Female'), ('DB15GM', 'DB-15 Gameport Male'), ('DB15GF', 'DB-15 Gameport Female'), ('USBAM', 'USB A Male'), ('USBAF', 'USB A Female'), ('USBBM', 'USB B Male'), ('USBBF', 'USB B Female'), ('USBMICROBM', 'USB Micro B Male'), ('USBMICROBF', 'USB Micro B Female'), ('USBMINIBM', 'USB Mini B Male'), ('USBMINIBF', 'USB Mini B Female'), ('DIN5M', '5-Pin DIN Male'), ('DIN5F', '5-Pin DIN Female'), ('ADBM', 'ADB Male'), ('ADBF', 'ADB Female'), ('PS2M', 'PS/2 Male'), ('PS2F', 'PS/2 Female'), ('PIN4', '4-Pin Connector'), ('PIN6', '6-Pin Connector'), ('PIN8', '8-Pin Connector'), ('MM35M', '3.5MM Male'), ('MM35F', '3.5MM Female'), ('MM63M', '6.3MM Male'), ('MM63F', '6.3MM Female'), ('XLRM', 'XLR Male'), ('XLRF', 'XLR Female'), ('RCAM', 'RCA Male'), ('RCAF', 'RCA Female'), ('MDAM', 'DB-9 MDA Male'), ('MDAF', 'DB-9 MDA Female'), ('CGAM', 'DB-9 CGA Male'), ('CGAF', 'DB-9 CGA Female'), ('EGAM', 'DB-9 EGA Male'), ('EGAF', 'DB-9 EGA Female'), ('VGAM', 'DB-15 VGA Male'), ('VGAF', 'DB-15 VGA Female'), ('DVIDDM', 'DVI-D Dual-Link Male'), ('DVIDDF', 'DVI-D Dual-Link Female'), ('DVIDSM', 'DVI-D Single-Link Male'), ('DVIDSF', 'DVI-D Single-Link Female'), ('DVIIDM', 'DVI-I Dual-Link Male'), ('DVIIDF', 'DVI-I Dual-Link Female'), ('DVIISM', 'DVI-I Single-Link Male'), ('DVIISF', 'DVI-I Single-Link Female'), ('DVIAM', 'DVI-A Male'), ('DVIAF', 'DVI-A Female'), ('HDMIM', 'HDMI Male'), ('HDMIF', 'HDMI Female'), ('MINIHDMIM', 'Mini HDMI Male'), ('MINIHDMIF', 'Mini HDMI Female'), ('MICROHDMIM', 'Micro HDMI Male'), ('MICROHDMIF', 'Micro HDMI Female'), ('DPM', 'DisplayPort Male'), ('DPF', 'DisplayPort Female'), ('MINIDPM', 'Mini DisplayPort Male'), ('MINIDPF', 'Mini DisplayPort Female')], default='OTHER', max_length=452, verbose_name='Interface B'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='interface',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('PIN', 'Pin Connector'), ('MM35', '3.5MM'), ('MM63', '6.3MM'), ('XLR', 'XLR'), ('RCA', 'RCA'), ('BT', 'Bluetooth'), ('MDA', 'MDA'), ('CGA', 'CGA'), ('EGA', 'EGA'), ('VGA', 'VGA'), ('DVI', 'DVI'), ('HDMI', 'HDMI'), ('DP', 'DisplayPort'), ('OTHER', 'Other')], default='USB', max_length=101),
        ),
    ]
