# Generated by Django 4.0.7 on 2022-11-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0021_alter_expansioncard_interface_alter_gpu_interface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cpu_world',
            field=models.TextField(blank=True, null=True),
        ),
    ]
