# Generated by Django 4.0.7 on 2022-11-13 13:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0029_alter_cables_interface_a_alter_cables_interface_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheral',
            name='interface',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('FLOPPY', 'Apple Floppy'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('PIN', 'Pin Connector'), ('MM35', '3.5MM'), ('MM63', '6.3MM'), ('XLR', 'XLR'), ('RCA', 'RCA'), ('BT', 'Bluetooth'), ('MDA', 'MDA'), ('CGA', 'CGA'), ('EGA', 'EGA'), ('VGA', 'VGA'), ('DVI', 'DVI'), ('HDMI', 'HDMI'), ('DP', 'DisplayPort'), ('OTHER', 'Other')], default='USB', max_length=108),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='type',
            field=models.CharField(choices=[('M', 'Mouse'), ('KB', 'Keyboard'), ('ZIP', 'Zip Drive'), ('FLOPPY', 'Floppy Drive'), ('HDD', 'Hard Drive'), ('DISC', 'Disc Drive'), ('GAME', 'Gamepad'), ('JOY', 'Joystick'), ('MIDI', 'Midi'), ('SPK', 'Speakers'), ('LCD', 'LCD'), ('CRT', 'CRT'), ('OTHER', 'Other')], default='M', max_length=10),
        ),
    ]
