# Generated by Django 4.0.7 on 2022-11-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0034_drive_alter_case_image_1_alter_case_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacity (MB)'),
        ),
    ]
