# Generated by Django 4.0.7 on 2022-11-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0036_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='ram1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram1', to='hardware.ram'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram2', to='hardware.ram'),
        ),
        migrations.AlterField(
            model_name='system',
            name='cpu1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu1', to='hardware.cpu'),
        ),
    ]
