# Generated by Django 4.0.7 on 2022-11-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0037_system_ram1_system_ram2_alter_system_cpu1'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='ram3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram3', to='hardware.ram'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram4', to='hardware.ram'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram5', to='hardware.ram'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram6', to='hardware.ram'),
        ),
    ]
