# Generated by Django 4.0.7 on 2022-11-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0038_system_ram3_system_ram4_system_ram5_system_ram6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='cpu1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu1', to='hardware.cpu'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram1', to='hardware.ram'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram2', to='hardware.ram'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram3', to='hardware.ram'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram4', to='hardware.ram'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram5', to='hardware.ram'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram6', to='hardware.ram'),
        ),
    ]
