# Generated by Django 4.0.7 on 2022-11-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0039_alter_system_cpu1_alter_system_ram1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='ram1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram1', to='hardware.ram'),
        ),
    ]
