# Generated by Django 4.0.7 on 2022-11-13 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0040_alter_system_ram1'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='hardware.case'),
        ),
        migrations.AddField(
            model_name='system',
            name='cpu2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu2', to='hardware.cpu', verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive1', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive2', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive3', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive4', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive5', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive6', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive7', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive8',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive8', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='expansion1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expansion1', to='hardware.expansioncard', verbose_name='Expansion Card'),
        ),
        migrations.AddField(
            model_name='system',
            name='expansion2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expansion2', to='hardware.expansioncard', verbose_name='Expansion Card'),
        ),
        migrations.AddField(
            model_name='system',
            name='expansion3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expansion3', to='hardware.expansioncard', verbose_name='Expansion Card'),
        ),
        migrations.AddField(
            model_name='system',
            name='expansion4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expansion4', to='hardware.expansioncard', verbose_name='Expansion Card'),
        ),
        migrations.AddField(
            model_name='system',
            name='expansion5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expansion5', to='hardware.expansioncard', verbose_name='Expansion Card'),
        ),
        migrations.AddField(
            model_name='system',
            name='expansion6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expansion6', to='hardware.expansioncard', verbose_name='Expansion Card'),
        ),
        migrations.AddField(
            model_name='system',
            name='gpu1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpu1', to='hardware.gpu', verbose_name='GPU'),
        ),
        migrations.AddField(
            model_name='system',
            name='gpu2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpu2', to='hardware.gpu', verbose_name='GPU'),
        ),
        migrations.AddField(
            model_name='system',
            name='motherboard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboard', to='hardware.motherboard'),
        ),
        migrations.AddField(
            model_name='system',
            name='nic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nic', to='hardware.nic', verbose_name='NIC'),
        ),
        migrations.AddField(
            model_name='system',
            name='os',
            field=models.CharField(blank=True, max_length=200, verbose_name='Operating System'),
        ),
        migrations.AddField(
            model_name='system',
            name='psu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psu', to='hardware.psu', verbose_name='PSU'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram10', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram11',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram11', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram12',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram12', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram13',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram13', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram14',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram14', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram15',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram15', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram16',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram16', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram7', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram8',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram8', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram9',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram9', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='system',
            name='soundcard1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soundcard1', to='hardware.soundcard', verbose_name='Sound Card'),
        ),
        migrations.AddField(
            model_name='system',
            name='soundcard2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soundcard2', to='hardware.soundcard', verbose_name='Sound Card'),
        ),
        migrations.AlterField(
            model_name='system',
            name='cpu1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu1', to='hardware.cpu', verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram1', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram2', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram3', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram4', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram5', to='hardware.ram', verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ram6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram6', to='hardware.ram', verbose_name='RAM'),
        ),
    ]
