# Generated by Django 4.0.7 on 2022-11-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0042_system_image_1_system_image_2_system_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='interface',
            field=models.CharField(choices=[('FLOPPYEDGE', '34-Pin Floppy Edge'), ('FLOPPY', '34-Pin Floppy'), ('APPLE', 'Apple 20-Pin'), ('IDE', 'IDE'), ('SCSI', 'SCSI'), ('SATA', 'SATA'), ('M240', 'M.2 2240'), ('M280', 'M.2 2280')], default='FLOPPYEDGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='psu',
            name='spec',
            field=models.CharField(choices=[('PROP', 'Proprietary'), ('AT', 'AT'), ('AXT20', '20-pin ATX'), ('ATX24', '24-pin ATX'), ('ATX2_4', '20+4-pin ATX')], default='AT', max_length=6),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='io_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='sound_cards', verbose_name='IO Panel'),
        ),
    ]
