# Generated by Django 4.0.7 on 2022-11-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0043_alter_drive_interface_alter_psu_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
