# Generated by Django 4.0.7 on 2022-11-21 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0046_alter_cable_interface_a_alter_cable_interface_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='drive10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive10', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive11',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive11', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive12',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive12', to='hardware.drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='system',
            name='drive9',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive9', to='hardware.drive', verbose_name='Drive'),
        ),
    ]
