# Generated by Django 4.0.7 on 2023-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0053_alter_cable_interface_a_alter_cable_interface_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(max_length=255, null=True, upload_to='systems')),
                ('image2', models.ImageField(max_length=255, null=True, upload_to='systems')),
                ('image3', models.ImageField(max_length=255, null=True, upload_to='systems')),
                ('image4', models.ImageField(max_length=255, null=True, upload_to='systems')),
            ],
        ),
    ]
