# Generated by Django 4.0.7 on 2023-04-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0054_microprop'),
    ]

    operations = [
        migrations.AddField(
            model_name='microprop',
            name='type',
            field=models.CharField(choices=[('MICRO', 'Microcomputer'), ('PROP', 'Proprietary')], default='PROP', max_length=20),
        ),
    ]
