# Generated by Django 4.0.7 on 2023-04-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0055_microprop_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microprop',
            old_name='image1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='microprop',
            old_name='image2',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='microprop',
            old_name='image3',
            new_name='image_3',
        ),
        migrations.RenameField(
            model_name='microprop',
            old_name='image4',
            new_name='image_4',
        ),
    ]
