# Generated by Django 4.0.7 on 2023-04-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0056_rename_image1_microprop_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microprop',
            name='image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='systems'),
        ),
        migrations.AlterField(
            model_name='microprop',
            name='image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='systems'),
        ),
        migrations.AlterField(
            model_name='microprop',
            name='image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='systems'),
        ),
        migrations.AlterField(
            model_name='microprop',
            name='image_4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='systems'),
        ),
    ]
