# Generated by Django 4.0.7 on 2023-05-01 20:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0057_alter_microprop_image_1_alter_microprop_image_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microprop',
            options={'verbose_name': 'Microcomputer/Proprietary System', 'verbose_name_plural': 'Microcomputers/Proprietary Systems'},
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='interface',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('JOY', 'Joystick'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('FLOPPY', 'Floppy'), ('CASS', 'Cassette'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('PIN', 'Pin Connector'), ('MM35', '3.5MM'), ('MM63', '6.3MM'), ('XLR', 'XLR'), ('RCA', 'RCA'), ('BT', 'Bluetooth'), ('MDA', 'MDA'), ('CGA', 'CGA'), ('EGA', 'EGA'), ('VGA', 'VGA'), ('DVI', 'DVI'), ('HDMI', 'HDMI'), ('DP', 'DisplayPort'), ('OTHER', 'Other')], default='USB', max_length=117),
        ),
    ]
