# Generated by Django 4.0.7 on 2023-05-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0058_alter_microprop_options_alter_peripheral_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheral',
            name='type',
            field=models.CharField(choices=[('M', 'Mouse'), ('KB', 'Keyboard'), ('ZIP', 'Zip Drive'), ('FLOPPY', 'Floppy Drive'), ('CASS', 'Cassette Player'), ('HDD', 'Hard Drive'), ('DISC', 'Disc Drive'), ('GAME', 'Gamepad'), ('JOY', 'Joystick'), ('MIDI', 'Midi'), ('SPK', 'Speakers'), ('LCD', 'LCD'), ('CRT', 'CRT'), ('OTHER', 'Other')], default='M', max_length=10),
        ),
    ]
