# Generated by Django 4.0.7 on 2023-08-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0059_alter_peripheral_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=1)),
                ('usage', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Single Board Computer',
                'verbose_name_plural': 'Single Board Computers',
            },
        ),
    ]
