# Generated by Django 4.0.7 on 2023-08-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0060_sbc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbc',
            options={'verbose_name': 'Single-board Computer', 'verbose_name_plural': 'Single-board Computers'},
        ),
    ]
