# Generated by Django 4.0.7 on 2023-11-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0061_alter_sbc_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='gpu',
            field=models.CharField(default='changeme', max_length=32, verbose_name='GPU'),
            preserve_default=False,
        ),
    ]
