# Generated by Django 4.0.7 on 2023-11-26 23:34

from django.db import migrations, models
import django.db.models.deletion
import hardware.models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0062_gpu_gpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='bottom_img',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='top_img',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=hardware.models.get_upload_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hardware.imagealbum')),
            ],
        ),
        migrations.AddField(
            model_name='cpu',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='hardware.imagealbum'),
        ),
    ]
