# Generated by Django 4.2.7 on 2023-12-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0062_gpu_gpu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System',
        ),
    ]
