# Generated by Django 4.2.7 on 2023-12-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0063_delete_system'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CPU',
            new_name='CPUOld',
        ),
    ]
