# Generated by Django 4.0.7 on 2023-11-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0063_imagealbum_remove_cpu_bottom_img_remove_cpu_top_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='type',
            field=models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('SOUND', 'Sound Card'), ('EXPAND', 'Expansion Card'), ('NIC', 'NIC'), ('MB', 'Motherboard'), ('PSU', 'PSU'), ('DRIVE', 'Drive'), ('CASE', 'Case'), ('SYS', 'System'), ('PERIPH', 'Peripheral'), ('CABLE', 'Cable')], default='CPU', max_length=10),
        ),
    ]
