# Generated by Django 4.2.7 on 2023-12-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0065_hardware_cpu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CPUOld',
        ),
    ]
