# Generated by Django 4.2.7 on 2023-12-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0067_rename_gpu_gpuold'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('gpu_brand', models.CharField(max_length=32, verbose_name='GPU')),
                ('interface', models.CharField(choices=[('ISA', '8-bit ISA'), ('ISA16', '16-bit ISA'), ('VLB', 'VLB'), ('PCI', 'PCI'), ('PCIX32', 'PCI-X 32-bit'), ('PCIX64', 'PCI-X 64-bit'), ('PCMCIA', 'PCMCIA'), ('AGP', 'AGP'), ('AGP2', 'AGP 2x'), ('AGP4', 'AGP 4x'), ('AGP8', 'AGP 8x'), ('PCIE1', 'PCIe x1'), ('PCIE4', 'PCIe x4'), ('PCIE8', 'PCIe x8'), ('PCIE16', 'PCIe x16'), ('M2', 'M.2 2230')], default='ISA', max_length=10)),
                ('mda', models.IntegerField(default=0, verbose_name='MDA Ports')),
                ('cga', models.IntegerField(default=0, verbose_name='CGA Ports')),
                ('composite', models.IntegerField(default=0, verbose_name='Composite Ports')),
                ('vga', models.IntegerField(default=0, verbose_name='VGA Ports')),
                ('svideo', models.IntegerField(default=0, verbose_name='S-Video Ports')),
                ('component', models.IntegerField(default=0, verbose_name='Component Ports')),
                ('dvi', models.IntegerField(default=0, verbose_name='DVI Ports')),
                ('hdmi', models.IntegerField(default=0, verbose_name='HDMI Ports')),
                ('minihdmi', models.IntegerField(default=0, verbose_name='Mini HDMI Ports')),
                ('microhdmi', models.IntegerField(default=0, verbose_name='Micro HDMI Ports')),
                ('dp', models.IntegerField(default=0, verbose_name='Displayport Ports')),
                ('minidp', models.IntegerField(default=0, verbose_name='Mini DisplayPort Ports')),
                ('other', models.IntegerField(default=0, verbose_name='Other Ports (Use notes)')),
            ],
            options={
                'verbose_name': 'GPU',
                'verbose_name_plural': 'GPUs',
            },
            bases=('hardware.hardware',),
        ),
    ]
