# Generated by Django 4.2.7 on 2023-12-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0069_delete_gpuold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoundCard',
            new_name='SoundCardOld',
        ),
    ]
