# Generated by Django 4.2.7 on 2023-12-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0070_rename_soundcard_soundcardold'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundCard',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('sb', models.CharField(max_length=200, verbose_name='SB Compatibility')),
                ('interface', models.CharField(choices=[('ISA', '8-bit ISA'), ('ISA16', '16-bit ISA'), ('VLB', 'VLB'), ('PCI', 'PCI'), ('PCIX32', 'PCI-X 32-bit'), ('PCIX64', 'PCI-X 64-bit'), ('PCMCIA', 'PCMCIA'), ('AGP', 'AGP'), ('AGP2', 'AGP 2x'), ('AGP4', 'AGP 4x'), ('AGP8', 'AGP 8x'), ('PCIE1', 'PCIe x1'), ('PCIE4', 'PCIe x4'), ('PCIE8', 'PCIe x8'), ('PCIE16', 'PCIe x16'), ('M2', 'M.2 2230')], default='ISA', max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('hardware.hardware',),
        ),
    ]
