# Generated by Django 4.2.7 on 2023-12-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0071_soundcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoundCardOld',
        ),
    ]
