# Generated by Django 4.2.7 on 2023-12-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0072_delete_soundcardold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpansionCard',
            new_name='ExpansionCardOld',
        ),
    ]
