# Generated by Django 4.2.7 on 2023-12-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0075_delete_expansioncardold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NIC',
            new_name='NICOld',
        ),
    ]
