# Generated by Django 4.2.7 on 2023-12-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0076_rename_nic_nicold'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('wireless', models.BooleanField()),
                ('speed', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('G', 'G'), ('N', 'N'), ('AC', 'AC'), ('AX', 'AX'), ('10', '10 Megabit'), ('100', '10/100 Megabit'), ('1000', 'Gigabit'), ('2500', '2.5 Gigabit'), ('10G', '10 Gigabit')], default='10', max_length=7)),
                ('interface', models.CharField(choices=[('ISA', '8-bit ISA'), ('ISA16', '16-bit ISA'), ('VLB', 'VLB'), ('PCI', 'PCI'), ('PCIX32', 'PCI-X 32-bit'), ('PCIX64', 'PCI-X 64-bit'), ('PCMCIA', 'PCMCIA'), ('AGP', 'AGP'), ('AGP2', 'AGP 2x'), ('AGP4', 'AGP 4x'), ('AGP8', 'AGP 8x'), ('PCIE1', 'PCIe x1'), ('PCIE4', 'PCIe x4'), ('PCIE8', 'PCIe x8'), ('PCIE16', 'PCIe x16'), ('M2', 'M.2 2230')], default='ISA', max_length=6)),
                ('aui', models.IntegerField(default=0, verbose_name='AUI Ports')),
                ('bnc', models.IntegerField(default=0, verbose_name='BNC Ports')),
                ('tp', models.IntegerField(default=0, verbose_name='Ethernet Ports')),
            ],
            options={
                'verbose_name': 'NIC',
                'verbose_name_plural': 'NICs',
            },
            bases=('hardware.hardware',),
        ),
    ]
