# Generated by Django 4.2.7 on 2023-12-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0077_nic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motherboard',
            new_name='MotherboardOld',
        ),
        migrations.DeleteModel(
            name='NICOld',
        ),
    ]
