# Generated by Django 4.2.7 on 2023-12-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0078_rename_motherboard_motherboardold_delete_nicold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('form_factor', models.CharField(choices=[('AT', 'AT'), ('BABYAT', 'Baby AT'), ('ATX', 'ATX'), ('EATX', 'E-ATX'), ('MATX', 'Micro ATX'), ('ITX', 'Mini ITX'), ('PROP', 'Proprietary')], default='ATX', max_length=6)),
                ('socket', models.CharField(max_length=200)),
                ('isa', models.IntegerField(default=0, verbose_name='8-bit ISA Slots')),
                ('isa16', models.IntegerField(default=0, verbose_name='16-bit ISA Slots')),
                ('vlb', models.IntegerField(default=0, verbose_name='VLB Slots')),
                ('pci', models.IntegerField(default=0, verbose_name='PCI Slots')),
                ('agp', models.IntegerField(default=0, verbose_name='AGP Slots')),
                ('pcie1', models.IntegerField(default=0, verbose_name='PCIe x1 Slots')),
                ('pcie4', models.IntegerField(default=0, verbose_name='PCIe x4 Slots')),
                ('pcie8', models.IntegerField(default=0, verbose_name='PCIe x8 Slots')),
                ('pcie16', models.IntegerField(default=0, verbose_name='PCIe x16 Slots')),
                ('ram', models.IntegerField(default=0, verbose_name='RAM Slots')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('hardware.hardware',),
        ),
    ]
