# Generated by Django 4.2.7 on 2023-12-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0079_motherboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PSU',
            new_name='PSUOld',
        ),
        migrations.DeleteModel(
            name='MotherboardOld',
        ),
    ]
