# Generated by Django 4.2.7 on 2023-12-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0080_rename_psu_psuold_delete_motherboardold'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('wattage', models.IntegerField()),
                ('spec', models.CharField(choices=[('PROP', 'Proprietary'), ('AT', 'AT'), ('AXT20', '20-pin ATX'), ('ATX24', '24-pin ATX'), ('ATX2_4', '20+4-pin ATX')], default='AT', max_length=6)),
                ('minus5v', models.BooleanField(verbose_name='-5v rail')),
                ('molex', models.IntegerField(default=0, verbose_name='Molex Connectors')),
                ('floppy', models.IntegerField(default=0, verbose_name='Floppy Connectors')),
                ('sata', models.IntegerField(default=0, verbose_name='SATA Connectors')),
                ('cpu4pin', models.IntegerField(default=0, verbose_name='4-pin CPU Connectors')),
                ('cpu8pin', models.IntegerField(default=0, verbose_name='8-pin CPU Connectors')),
                ('pcie6pin', models.IntegerField(default=0, verbose_name='6-pin PCIe Connectors')),
                ('pcie8pin', models.IntegerField(default=0, verbose_name='8-pin PCIe Connectors')),
            ],
            options={
                'verbose_name': 'PSU',
                'verbose_name_plural': 'PSUs',
            },
            bases=('hardware.hardware',),
        ),
    ]
