# Generated by Django 4.2.7 on 2023-12-02 15:56

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0084_rename_case_caseold_delete_driveold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('mb_support', multiselectfield.db.fields.MultiSelectField(choices=[('AT', 'AT'), ('BABYAT', 'Baby AT'), ('ATX', 'ATX'), ('EATX', 'E-ATX'), ('MATX', 'Micro ATX'), ('ITX', 'Mini ITX'), ('PROP', 'Proprietary')], default='ATX', max_length=32, verbose_name='Motherboard Compatibility')),
            ],
            options={
                'verbose_name': 'Case',
            },
            bases=('hardware.hardware',),
        ),
    ]
