# Generated by Django 4.2.7 on 2023-12-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0085_case'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MicroProp',
            new_name='MicroPropOld',
        ),
        migrations.DeleteModel(
            name='CaseOld',
        ),
    ]
