# Generated by Django 4.2.7 on 2023-12-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0086_rename_microprop_micropropold_delete_caseold'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroProp',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('type', models.CharField(choices=[('MICRO', 'Microcomputer'), ('PROP', 'Proprietary')], default='PROP', max_length=20)),
            ],
            options={
                'verbose_name': 'Microcomputer/Proprietary System',
                'verbose_name_plural': 'Microcomputers/Proprietary Systems',
            },
            bases=('hardware.hardware',),
        ),
    ]
