# Generated by Django 4.2.7 on 2023-12-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0087_microprop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peripheral',
            new_name='PeripheralOld',
        ),
        migrations.DeleteModel(
            name='MicroPropOld',
        ),
    ]
