# Generated by Django 4.2.7 on 2023-12-02 16:01

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0088_rename_peripheral_peripheralold_delete_micropropold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('type', models.CharField(choices=[('M', 'Mouse'), ('KB', 'Keyboard'), ('ZIP', 'Zip Drive'), ('FLOPPY', 'Floppy Drive'), ('CASS', 'Cassette Player'), ('HDD', 'Hard Drive'), ('DISC', 'Disc Drive'), ('GAME', 'Gamepad'), ('JOY', 'Joystick'), ('MIDI', 'Midi'), ('SPK', 'Speakers'), ('LCD', 'LCD'), ('CRT', 'CRT'), ('OTHER', 'Other')], default='M', max_length=10)),
                ('interface', multiselectfield.db.fields.MultiSelectField(choices=[('SERIAL', 'Serial'), ('PARALLEL', 'Parallel'), ('GAME', 'Gameport'), ('JOY', 'Joystick'), ('MIDI', 'Midi'), ('ADB', 'ADB'), ('FLOPPY', 'Floppy'), ('CASS', 'Cassette'), ('SCSI', 'SCSI'), ('PS2', 'PS/2'), ('USB', 'USB'), ('PIN', 'Pin Connector'), ('MM35', '3.5MM'), ('MM63', '6.3MM'), ('XLR', 'XLR'), ('RCA', 'RCA'), ('BT', 'Bluetooth'), ('MDA', 'MDA'), ('CGA', 'CGA'), ('EGA', 'EGA'), ('VGA', 'VGA'), ('DVI', 'DVI'), ('HDMI', 'HDMI'), ('DP', 'DisplayPort'), ('OTHER', 'Other')], default='USB', max_length=117)),
            ],
            options={
                'verbose_name': 'Perhipheral',
                'verbose_name_plural': 'Peripherals',
            },
            bases=('hardware.hardware',),
        ),
    ]
