# Generated by Django 4.2.7 on 2023-12-02 16:10

from django.db import migrations, models
import django.db.models.deletion
import hardware.models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0091_cable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=hardware.models.get_upload_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hardware.hardware')),
            ],
        ),
        migrations.DeleteModel(
            name='CableOld',
        ),
    ]
