# Generated by Django 4.2.7 on 2023-12-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0092_image_delete_cableold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='album',
            new_name='part',
        ),
    ]
