# Generated by Django 4.2.7 on 2023-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0093_rename_album_image_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
