# Generated by Django 4.2.7 on 2023-12-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0094_alter_hardware_brand_alter_hardware_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFacor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='mb_support',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='form_factor',
        ),
        migrations.AddField(
            model_name='case',
            name='mb_support',
            field=models.ManyToManyField(to='hardware.formfacor', verbose_name='Motherboard Compatibility'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='form_factor',
            field=models.ManyToManyField(to='hardware.formfacor'),
        ),
    ]
