# Generated by Django 4.2.7 on 2023-12-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0096_rename_formfacor_formfactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='form_factor',
        ),
        migrations.AddField(
            model_name='motherboard',
            name='form_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.formfactor'),
        ),
    ]
