# Generated by Django 4.2.7 on 2023-12-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0097_remove_motherboard_form_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='expansioncard',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='soundcard',
            name='interface',
        ),
    ]
