# Generated by Django 4.2.7 on 2023-12-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0099_expansioncard_interface_gpu_interface_nic_interface_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name': 'Slot', 'verbose_name_plural': 'Slots'},
        ),
        migrations.RemoveField(
            model_name='drive',
            name='interface',
        ),
    ]
