# Generated by Django 4.2.7 on 2023-12-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0100_driveinterface_rename_slots_slot_alter_slot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='interface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.driveinterface'),
        ),
    ]
