# Generated by Django 4.2.7 on 2023-12-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0101_drive_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeripheralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Peripheral Type',
                'verbose_name_plural': 'Peripheral Types',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Ports',
            },
        ),
        migrations.AlterModelOptions(
            name='driveinterface',
            options={'verbose_name': 'Drive Interface', 'verbose_name_plural': 'Drive Interfaces'},
        ),
        migrations.RemoveField(
            model_name='peripheral',
            name='type',
        ),
        migrations.AddField(
            model_name='peripheral',
            name='port',
            field=models.ManyToManyField(to='hardware.port'),
        ),
    ]
