# Generated by Django 4.2.7 on 2023-12-02 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0103_peripheral_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Cable Type',
                'verbose_name_plural': 'Cable Types',
            },
        ),
        migrations.RenameField(
            model_name='peripheral',
            old_name='port',
            new_name='ports',
        ),
        migrations.AddField(
            model_name='cable',
            name='ports',
            field=models.ManyToManyField(to='hardware.port'),
        ),
        migrations.AddField(
            model_name='cable',
            name='type1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.cabletype'),
        ),
    ]
