# Generated by Django 4.2.7 on 2023-12-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0104_cabletype_rename_port_peripheral_ports_cable_ports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='type',
        ),
    ]
