# Generated by Django 4.2.7 on 2023-12-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0105_remove_cable_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cable',
            old_name='type1',
            new_name='type',
        ),
    ]
