# Generated by Django 4.2.7 on 2023-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0107_remove_cable_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='ports_a',
            field=models.ManyToManyField(related_name='cable_a', to='hardware.port'),
        ),
        migrations.AddField(
            model_name='cable',
            name='ports_b',
            field=models.ManyToManyField(related_name='cable_b', to='hardware.port'),
        ),
    ]
