# Generated by Django 4.2.7 on 2023-12-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0108_cable_ports_a_cable_ports_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='interface_a',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='interface_b',
        ),
        migrations.AlterField(
            model_name='cable',
            name='ports_a',
            field=models.ManyToManyField(related_name='cable_a', to='hardware.port', verbose_name='Ports (A Side)'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='ports_b',
            field=models.ManyToManyField(related_name='cable_b', to='hardware.port', verbose_name='Ports (B Side)'),
        ),
    ]
