# Generated by Django 4.2.7 on 2023-12-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0109_remove_cable_interface_a_remove_cable_interface_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cable',
            old_name='ports_a',
            new_name='connectors_a',
        ),
    ]
