# Generated by Django 4.2.7 on 2023-12-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0110_rename_ports_a_cable_connectors_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cable',
            old_name='ports_b',
            new_name='connectors_b',
        ),
    ]
