# Generated by Django 4.2.7 on 2023-12-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0111_rename_ports_b_cable_connectors_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='connectors_a',
            field=models.ManyToManyField(related_name='cable_a', to='hardware.port', verbose_name='Connector(s) (A Side)'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='connectors_b',
            field=models.ManyToManyField(related_name='cable_b', to='hardware.port', verbose_name='Connector(s) (B Side)'),
        ),
    ]
