# Generated by Django 4.2.7 on 2023-12-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0112_alter_cable_connectors_a_alter_cable_connectors_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheral',
            name='ports',
            field=models.ManyToManyField(blank=True, to='hardware.port'),
        ),
    ]
