# Generated by Django 4.2.7 on 2023-12-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0113_alter_peripheral_ports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peripheral',
            name='interface',
        ),
    ]
