# Generated by Django 4.2.7 on 2023-12-03 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0114_remove_peripheral_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('os', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('hardware.hardware',),
        ),
        migrations.AddField(
            model_name='cpu',
            name='installed_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpus', to='hardware.system'),
        ),
    ]
