# Generated by Django 4.2.7 on 2023-12-03 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0115_system_cpu_installed_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='installed_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram', to='hardware.system'),
        ),
        migrations.AlterField(
            model_name='system',
            name='os',
            field=models.CharField(max_length=64, verbose_name='OS'),
        ),
    ]
